### PR TITLE
Suggested changes

### PR DESCRIPTION
**Pull request by MartijnHols**
http://forums.heroesofnewerth.com/showthread.php?491921-Advanced-Shopping-Library&p=15732331&viewfull=1#post15732331

### CODE REVIEW

**Comment by MartijnHols** [comment]
After our talk on IRC last night it got me thinking and I figured you were right about throttling item purchases to simulate human behavior. Therefore I added it back in (without breaking the wards again) and also added a few more human like behavioral things. I also considered difficulty gating (as you can see in the inline comments) which you can implement easily if you want. (I think it would be fun)

I have implemented this version in my GlaciusSupportBot and with a simple DetermineNextItemDef I managed to get it to work exactly as I wanted: https://github.com/Zerotorescue/HoN-Bots/blob/master/GlaciusSupportBot/glacius_main.lua#L929

**Comment by Schnarchnase** [comment]
Working through your pull request atm.. Commenting on your commits why and in which form they will be (not) implemented.

**Comment by MartijnHols** [comment]
She's all yours. I imagine it's probably easiest if you didn't merge the commit but instead manually copy-pasted the changes. That way you have absolute control over what goes in and what not and you know exactly what gets changed. It may be a bit more work, but if it contributes to your understanding and liking of the code then I think that is worth it.

Do note I discovered and fixed a bug; at https://github.com/Zerotorescue/Hon-Bots-1/blob/master/advancedShopping.lua#L1473 you need to remove the first "not" or the entire check will work the opposite way to how it was intended.

Also, I noticed I broke the item sorting since my boots were being moved to stash after a while (I think, could have been sold too, no way to know), I figured trying to fix it is useless if you're going to be implementing it your own way so I'm just mentioning it so you could look into it.

Final two suggestions; a toggle to be able to determine if my bot will be allowed to use the courier if it isn't flying. In most games I play I would probably never use a ground courier as a support since it would take too long and most other players have a higher priority.
Second, being able to configure at what HP level health pots are being bought would be nice. 60% is a bit high for my bot and he keeps on buying them (might also be the result of some other changes, I'm sure you'll figure it out).

**Comment by MartijnHols** [comment]
Right. Check the latest state of the utility function. I removed the pregame overriding functions as these were no longer needed since the utility value is set to 99 during pregame and movement is suspended while buying so it also works with your WitchSlayerBot.

**Pull request closed without merging**
